/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 授權客戶端
 */
@Data
@Accessors(chain = true)
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "oauth_client_details", indexes = {
        @Index(name = "PRIMARY", unique = true, columnList = "client_id ASC")
})
public class OauthClientDetails implements Serializable {

    private static final long serialVersionUID = -1410343569;
    @Id
    @Column(name = "client_id", unique = true, nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    private String clientId;
    @Column(name = "client_secret", nullable = false, length = 256)
    @NotNull
    @Size(max = 256)
    private String clientSecret;
    @Column(name = "web_server_redirect_uri", length = 256)
    @Size(max = 256)
    private String webServerRedirectUri;
    @Column(name = "access_token_validity", precision = 10)
    private Integer accessTokenValidity;
    @Column(name = "refresh_token_validity", precision = 10)
    private Integer refreshTokenValidity;
    @Column(name = "auto_approve", nullable = false, precision = 1)
    @NotNull
    private Boolean autoApprove;
    @Column(name = "created_by", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    private String createdBy;
    @Column(name = "created_date", nullable = false)
    @NotNull
    private LocalDateTime createdDate;
    @Column(name = "last_modified_by", length = 100)
    @Size(max = 100)
    private String lastModifiedBy;
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;
}
