/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.Size;


/**
 * 更新Token列表
 */
@Data
@Accessors(chain = true)
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "oauth_refresh_token")
public class OauthRefreshToken implements Serializable {

    private static final long serialVersionUID = 1869721584;
    @Id
    @Column(name = "token_id", length = 256)
    @Size(max = 256)
    private String tokenId;
    @Lob
    @Column(name = "token", length = 65535)
    @Size(max = 65535)
    private byte[] token;
    @Lob
    @Column(name = "authentication", length = 65535)
    @Size(max = 65535)
    private byte[] authentication;
}
