/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 角色對應權限範圍
 */
@Data
@Accessors(chain = true)
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "role_scop", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"role_id", "scop_id"})
}, indexes = {
        @Index(name = "PRIMARY", unique = true, columnList = "ser_id ASC"),
        @Index(name = "role_scop_scop_id_fk_2", columnList = "scop_id ASC"),
        @Index(name = "role_scop_uk_1", unique = true, columnList = "role_id ASC, scop_id ASC")
})
public class RoleScop implements Serializable {

    private static final long serialVersionUID = -98421189;
    @Id
    @Column(name = "ser_id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String serId;
    @Column(name = "role_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String roleId;
    @Column(name = "scop_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String scopId;
    @Column(name = "created_by", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    private String createdBy;
    @Column(name = "created_date", nullable = false)
    @NotNull
    private LocalDateTime createdDate;
    @Column(name = "last_modified_by", length = 100)
    @Size(max = 100)
    private String lastModifiedBy;
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;
}
