/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 使用者
 */
@Data
@Accessors(chain = true)
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "user_account", indexes = {
        @Index(name = "account", unique = true, columnList = "account ASC"),
        @Index(name = "PRIMARY", unique = true, columnList = "uid ASC")
})
public class UserAccount implements Serializable {

    private static final long serialVersionUID = -476753653;
    @Id
    @Column(name = "uid", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String uid;
    @Column(name = "account", unique = true, nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    private String account;
    @Column(name = "password", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    private String password;
    @Column(name = "enabled", nullable = false, precision = 1)
    @NotNull
    private Boolean enabled;
    @Column(name = "expired", nullable = false, precision = 1)
    @NotNull
    private Boolean expired;
    @Column(name = "locked", nullable = false, precision = 1)
    @NotNull
    private Boolean locked;
    @Column(name = "credentials_expired", nullable = false, precision = 1)
    @NotNull
    private Boolean credentialsExpired;
    @Column(name = "created_by", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    private String createdBy;
    @Column(name = "created_date", nullable = false)
    @NotNull
    private LocalDateTime createdDate;
    @Column(name = "last_modified_by", length = 100)
    @Size(max = 100)
    private String lastModifiedBy;
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;
}
