/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 使用者對應角色
 */
@Data
@Accessors(chain = true)
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "user_role_map", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"uid", "role_id"})
}, indexes = {
        @Index(name = "account_role_map_role_id_fk_1", columnList = "role_id ASC"),
        @Index(name = "account_role_map_uk_1", unique = true, columnList = "uid ASC, role_id ASC"),
        @Index(name = "PRIMARY", unique = true, columnList = "sid ASC")
})
public class UserRoleMap implements Serializable {

    private static final long serialVersionUID = -1070484641;
    @Id
    @Column(name = "sid", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String sid;
    @Column(name = "uid", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String uid;
    @Column(name = "role_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    private String roleId;
    @Column(name = "created_by", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    private String createdBy;
    @Column(name = "created_date", nullable = false)
    @NotNull
    private LocalDateTime createdDate;
    @Column(name = "last_modified_by", length = 100)
    @Size(max = 100)
    private String lastModifiedBy;
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;

}
